CREATE TABLE "leads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vertical" text NOT NULL,
	"name" text NOT NULL,
	"business_name" text NOT NULL,
	"whatsapp_normalized" text NOT NULL,
	"email" text,
	"city" text,
	"state" char(2),
	"segment" text NOT NULL,
	"team_size" text NOT NULL,
	"monthly_volume" text NOT NULL,
	"current_tool" text NOT NULL,
	"main_pain" text NOT NULL,
	"desired_features" jsonb NOT NULL,
	"willingness_to_pay" text NOT NULL,
	"interview_permission" boolean DEFAULT false NOT NULL,
	"privacy_consent" boolean NOT NULL,
	"privacy_notice_version" text NOT NULL,
	"consented_at" timestamp with time zone NOT NULL,
	"answers" jsonb NOT NULL,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"utm_term" text,
	"utm_content" text,
	"gclid" text,
	"landing_path" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "leads_privacy_consent_true" CHECK ("leads"."privacy_consent" = true),
	CONSTRAINT "leads_whatsapp_digits" CHECK ("leads"."whatsapp_normalized" ~ '^[0-9]{10,15}$'),
	CONSTRAINT "leads_vertical_allowed" CHECK ("leads"."vertical" = 'assistencia-tecnica')
);
--> statement-breakpoint
CREATE UNIQUE INDEX "leads_vertical_whatsapp_unique" ON "leads" USING btree ("vertical","whatsapp_normalized");